name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      -
        name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: blueloveth
          password: ${{ secrets.ACR_PASSWORD }}
      -
        name: Build and Push Docker Image
        run: |
          export image_tag=registry.cn-hangzhou.aliyuncs.com/blueloveth/ipfs-cdn:${GITHUB_SHA:0:7}
          docker build -t $image_tag .
          docker push $image_tag
