name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: blueloveth
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    -
      name: Build and Push Docker Image
      run: |
        export image_tag=ipfs-cdn:${GITHUB_SHA:0:7}
        docker build -t $image_tag .
        docker push blueloveth/$image_tag
